name: pstime_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - ipywidgets
  - scanpy
  - decoupler-py
  - python-igraph
  - anndata
  - pip:
      - celltypist
      - pyslingshot
